export const ACTION_GET_MOVIES_REQUEST = 'ACTION_GET_MOVIES_REQUEST';
export const ACTION_GET_MOVIES_SUCCESS = 'ACTION_GET_MOVIES_SUCCESS';
export const ACTION_GET_MOVIES_FAILURE = 'ACTION_GET_MOVIES_FAILURE';

export const ACTION_GET_SERIES_REQUEST = 'ACTION_GET_SERIES_REQUEST';
export const ACTION_GET_SERIES_SUCCESS = 'ACTION_GET_SERIES_SUCCESS';
export const ACTION_GET_SERIES_FAILURE = 'ACTION_GET_SERIES_FAILURE';

export const ACTION_GET_FAMILY_REQUEST = 'ACTION_GET_FAMILY_REQUEST';
export const ACTION_GET_FAMILY_SUCCESS = 'ACTION_GET_FAMILY_SUCCESS';
export const ACTION_GET_FAMILY_FAILURE = 'ACTION_GET_FAMILY_FAILURE';

export const ACTION_GET_DOCUMENTARY_REQUEST = 'ACTION_GET_DOCUMENTARY_REQUEST';
export const ACTION_GET_DOCUMENTARY_SUCCESS = 'ACTION_GET_DOCUMENTARY_SUCCESS';
export const ACTION_GET_DOCUMENTARY_FAILURE = 'ACTION_GET_DOCUMENTARY_FAILURE';

export const ACTION_GET_GENRES_REQUEST = 'ACTION_GET_GENRES_REQUEST';
export const ACTION_GET_GENRES_SUCCESS = 'ACTION_GET_GENRES_SUCCESS';
export const ACTION_GET_GENRES_FAILURE = 'ACTION_GET_GENRES_FAILURE';
